name: Multi-Arch Docker Build & GHCR Push with Scout Scan

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write  # Required to push to GHCR

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write Dockerfile
        run: |
          cat <<EOF > Dockerfile
          # syntax=docker/dockerfile:1
          FROM node:18-slim

          WORKDIR /app

          COPY package*.json ./
          RUN npm ci --omit=dev

          COPY . .

          EXPOSE 80

          CMD ["npm", "start"]
          EOF

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push Multi-Arch Image (latest)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Docker Scout CVE Scan on Multi-Arch (:latest)
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ghcr.io/${{ github.repository }}:latest
          dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
