name: Multi-Arch Docker Build & GHCR Push

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write  # Required to push to GHCR

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
        include:
          - platform: linux/amd64
            tag: arm64-safe-amd64
          - platform: linux/arm64
            tag: arm64-safe-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push for ${{ matrix.platform }}
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ matrix.tag }}

      - name: Docker Scout Scan
        uses: docker/scout-action@v1
        with:
          image: ghcr.io/${{ github.repository }}:${{ matrix.tag }}
