name: Multi-Arch Docker Build & GHCR Push with SES Notifications

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write
  id-token: write  # REQUIRED for OIDC authentication

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
        include:
          - platform: linux/amd64
            tag: amd64
          - platform: linux/arm64
            tag: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write Dockerfile
        run: |
          cat <<EOF > Dockerfile
          FROM node:18-slim
          WORKDIR /app
          COPY package*.json ./
          RUN npm ci --omit=dev
          COPY . .
          EXPOSE 80
          CMD ["npm", "start"]
          EOF

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.username }}
          password: ${{ secrets.token }}

      - name: Build and Push Docker Image for ${{ matrix.platform }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ matrix.tag }}

      - name: Docker Scout CVE Scan for ${{ matrix.platform }}
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ghcr.io/${{ github.repository }}:${{ matrix.tag }}
          platform: ${{ matrix.platform }}
          dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}

  notify-success:
    needs: build-and-scan
    if: success()
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read  #Needed for assuming IAM role via OIDC
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::399359779313:role/dggfdbhch
          aws-region: us-east-1

      - name: Send SES success email
        run: |
          aws ses send-email \
            --from "${{ secrets.SES_FROM_ADDRESS }}" \
            --destination "ToAddresses=${{ secrets.SES_TO_ADDRESS }}" \
            --message "Subject={Data='✅ Docker Build Success'},Body={Text={Data='Build and scan for ${{ github.repository }} succeeded.'}}"

  notify-failure:
    needs: build-and-scan
    if: failure()
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::399359779313:role/role2g234
          aws-region: eu-north-1

      - name: Send SES failure email
        run: |
          aws ses send-email \
            --from "${{ secrets.SES_FROM_ADDRESS }}" \
            --destination "ToAddresses=${{ secrets.SES_TO_ADDRESS }}" \
            --message "Subject={Data='❌ Docker Build Failed'},Body={Text={Data='Build or scan for ${{ github.repository }} failed. Please check logs.'}}"
